apiVersion: v1
kind: Service
metadata:
  name: my-nest-app-service
  labels:
    app: my-nestjs-app
spec:
  selector:
    app: my-nestjs-app
  ports:
    - protocol: TCP
      port: 3000
  type: LoadBalancer